#!/usr/bin/env bash

set -xe

function workdir() {
    ORIGIN="$(cd "$(dirname "$0")" && pwd)"
    pushd .
    cd "$ORIGIN"
}

function add_all() {
    git add .
    git submodule foreach git add .
}

workdir
add_all

export AGENIX_REKEY_PRIMARY_IDENTITY="age1ax4x0pwe00clawkp5zn7qdf5e2tvuu0echvachd0pv5hm8hq9qnswqpzek"
export AGENIX_REKEY_PRIMARY_IDENTITY_ONLY=true

agenix --extra-flake-params "?submodules=1" rekey
