#!/usr/bin/env bash

set -xe

function workdir() {
    ORIGIN="$(cd "$(dirname "$0")" && pwd)"
    pushd .
    cd "$ORIGIN"
}

function add_all() {
    git add .
    git submodule foreach git add .
}

workdir
add_all

agenix  --extra-flake-params "?submodules=1" rekey
