#!/usr/bin/env bash

set -xe

function workdir() {
    ORIGIN="$(cd "$(dirname "$0")" && pwd)"
    pushd .
    cd "$ORIGIN"
}

workdir

git add .
git submodule foreach git add .

sudo nixos-rebuild switch --flake "${PWD}?submodules=1"

git submodule foreach git commit -am "autosave" || true
git commit -am "autosave" || true

popd
