#!/usr/bin/env bash

set -xe

function workdir() {
    ORIGIN="$(cd "$(dirname "$0")" && pwd)"
    pushd .
    cd "$ORIGIN"
}

workdir

git add .
sudo nixos-rebuild switch --flake $PWD
git commit -am "autosave"
git push

popd
