[
  ./age.nix
  ./autostart.nix
  ./cleanups.nix
  ./cosmic-keybindings.nix
  ./kde.nix
  ./dev-generic.nix
  ./dev-git.nix
  ./dev-llm.nix
  ./dev-cs.nix
  ./dev-scala.nix
  ./electron-wrappers.nix
  ./env-settings-generic.nix
  ./env-settings-desktop.nix
  ./firefox-notabbar.nix
  ./firefox.nix
  ./ghostty.nix
  ./htop.nix
  ./kitty.nix
  ./nushell.nix
  ./ssh.nix
  ./tailscale.nix
  ./tmux.nix
  ./vscodium.nix
  ./wezterm.nix
  ./zed.nix
  ./zsh.nix
]
