//! Unified bindings: trigger + effect pairs. Replaces the old split
//! between room device bindings and action rules. Every button-to-behavior
//! mapping is now an explicit binding in one flat list.
//!
//! ## Trigger types
//!
//! - `Button` — a switch button was pressed/held/released/double-tapped.
//!   Replaces the old `Tap`, `SwitchOn`, `SwitchOff` trigger variants.
//! - `PowerBelow` — a plug's power stayed below a threshold (kill switch).
//! - `At` — scheduled time trigger.
//!
//! ## Effect types
//!
//! Room-targeting effects (generated by Nix from switch-to-room sugar):
//! - `SceneCycle` — always cycle to next scene (wall switch on-button).
//! - `SceneToggle` — pure on/off toggle (no cycle window).
//! - `SceneToggleCycle` — 3-branch: fresh-on / cycle-in-window / off.
//! - `TurnOffRoom` — turn off a room group.
//! - `BrightnessStep` — step brightness up/down.
//! - `BrightnessMove` — continuous brightness change (hold).
//! - `BrightnessStop` — stop continuous brightness change (hold release).
//!
//! Device-targeting effects (same as old action rules):
//! - `Toggle`, `TurnOn`, `TurnOff`, `TurnOffAllZones`.

use serde::{Deserialize, Serialize};

use super::switch_model::Gesture;
use super::time_expr::TimeExpr;

/// One binding: a trigger condition paired with an effect to execute.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Binding {
    /// Stable human-readable name. Must be unique across all bindings.
    pub name: String,

    /// What event condition activates this binding.
    pub trigger: Trigger,

    /// What to do when the trigger fires.
    pub effect: Effect,
}

/// Event condition that activates a binding.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Trigger {
    /// A switch button event. Unified replacement for the old Tap,
    /// SwitchOn, and SwitchOff trigger variants.
    Button {
        device: String,
        button: String,
        gesture: Gesture,
    },

    /// A plug's real-time power reading stayed below `watts` for at
    /// least `for_seconds`. Requires the target plug to have the
    /// `"power"` capability.
    PowerBelow {
        device: String,
        watts: f64,
        for_seconds: u64,
    },

    /// Fires once per day at the specified local time. Accepts fixed
    /// times ("14:00") and sun-relative expressions ("sunset-01:00").
    At {
        time: TimeExpr,
    },
}

/// Command to execute when a trigger fires.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Effect {
    // ---- Room-targeting effects ----

    /// Always cycle to the next scene in the active time slot.
    /// Wall switch on-button behavior: no cycle window, no toggle-off.
    /// Every press advances the cycle unconditionally.
    SceneCycle {
        room: String,
    },

    /// Pure on/off toggle: if room is off → turn on with first scene,
    /// if room is on → turn off. No cycle window, no scene advancement.
    /// Designed for buttons that use hardware double-tap for cycling.
    SceneToggle {
        room: String,
    },

    /// Three-branch tap behavior:
    /// 1. If room is off → turn on with first scene
    /// 2. If within cycle window → advance to next scene
    /// 3. If outside cycle window → turn off
    SceneToggleCycle {
        room: String,
    },

    /// Turn off a room group with its configured transition.
    TurnOffRoom {
        room: String,
    },

    /// Step brightness up or down. Positive step = brighter.
    BrightnessStep {
        room: String,
        step: i16,
        transition: f64,
    },

    /// Start continuous brightness change (hold). Positive rate = brighter.
    BrightnessMove {
        room: String,
        rate: i16,
    },

    /// Stop continuous brightness change (hold release).
    BrightnessStop {
        room: String,
    },

    // ---- Device-targeting effects ----

    /// Toggle the target device: if ON → OFF, if OFF → ON.
    /// With `confirm_off_seconds`: turning OFF requires a double-tap
    /// within the confirmation window.
    Toggle {
        target: String,
        #[serde(default)]
        confirm_off_seconds: Option<f64>,
    },

    /// Turn the target device ON unconditionally.
    TurnOn {
        target: String,
    },

    /// Turn the target device OFF unconditionally.
    TurnOff {
        target: String,
    },

    /// Turn off every light zone (room group).
    TurnOffAllZones,
}

impl Trigger {
    /// The device friendly_name this trigger watches, if any.
    pub fn device(&self) -> Option<&str> {
        match self {
            Self::Button { device, .. }
            | Self::PowerBelow { device, .. } => Some(device),
            Self::At { .. } => None,
        }
    }
}

impl Effect {
    /// The room this effect targets, if it's a room-targeting effect.
    pub fn room(&self) -> Option<&str> {
        match self {
            Self::SceneCycle { room }
            | Self::SceneToggle { room }
            | Self::SceneToggleCycle { room }
            | Self::TurnOffRoom { room }
            | Self::BrightnessStep { room, .. }
            | Self::BrightnessMove { room, .. }
            | Self::BrightnessStop { room } => Some(room),
            _ => None,
        }
    }

    /// The device this effect targets, if it's a device-targeting effect.
    pub fn target(&self) -> Option<&str> {
        match self {
            Self::Toggle { target, .. }
            | Self::TurnOn { target }
            | Self::TurnOff { target } => Some(target),
            _ => None,
        }
    }

    /// For `Toggle` with `confirm_off_seconds`, the confirmation window.
    pub fn confirm_off_seconds(&self) -> Option<f64> {
        match self {
            Self::Toggle { confirm_off_seconds, .. } => *confirm_off_seconds,
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deserialize_button_scene_cycle() {
        let json = r#"{
            "name": "kitchen-on",
            "trigger": { "kind": "button", "device": "hue-s-kitchen", "button": "on", "gesture": "press" },
            "effect": { "kind": "scene_cycle", "room": "kitchen-cooker" }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        assert_eq!(binding.name, "kitchen-on");
        assert_eq!(binding.trigger.device(), Some("hue-s-kitchen"));
        assert_eq!(binding.effect.room(), Some("kitchen-cooker"));
        match &binding.trigger {
            Trigger::Button { button, gesture, .. } => {
                assert_eq!(button, "on");
                assert_eq!(*gesture, Gesture::Press);
            }
            other => panic!("expected Button, got {other:?}"),
        }
    }

    #[test]
    fn deserialize_button_toggle_plug() {
        let json = r#"{
            "name": "printer-toggle",
            "trigger": { "kind": "button", "device": "hue-ts-office", "button": "3", "gesture": "press" },
            "effect": { "kind": "toggle", "target": "z2m-p-printer" }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        assert_eq!(binding.effect.target(), Some("z2m-p-printer"));
    }

    #[test]
    fn deserialize_power_below() {
        let json = r#"{
            "name": "printer-kill",
            "trigger": { "kind": "power_below", "device": "z2m-p-printer", "watts": 5.0, "for_seconds": 300 },
            "effect": { "kind": "turn_off", "target": "z2m-p-printer" }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        match &binding.trigger {
            Trigger::PowerBelow { watts, for_seconds, .. } => {
                assert!((watts - 5.0).abs() < f64::EPSILON);
                assert_eq!(*for_seconds, 300);
            }
            other => panic!("expected PowerBelow, got {other:?}"),
        }
    }

    #[test]
    fn deserialize_brightness_step() {
        let json = r#"{
            "name": "kitchen-up",
            "trigger": { "kind": "button", "device": "hue-s-kitchen", "button": "up", "gesture": "press" },
            "effect": { "kind": "brightness_step", "room": "kitchen-cooker", "step": 25, "transition": 0.2 }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        match &binding.effect {
            Effect::BrightnessStep { step, transition, .. } => {
                assert_eq!(*step, 25);
                assert!((transition - 0.2).abs() < f64::EPSILON);
            }
            other => panic!("expected BrightnessStep, got {other:?}"),
        }
    }

    #[test]
    fn deserialize_scene_toggle() {
        let json = r#"{
            "name": "bedroom-toggle",
            "trigger": { "kind": "button", "device": "sonoff-ts-foo", "button": "1", "gesture": "press" },
            "effect": { "kind": "scene_toggle", "room": "bedroom" }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        match &binding.effect {
            Effect::SceneToggle { room } => assert_eq!(room, "bedroom"),
            other => panic!("expected SceneToggle, got {other:?}"),
        }
    }

    #[test]
    fn deserialize_scene_toggle_cycle() {
        let json = r#"{
            "name": "tap-2-kitchen",
            "trigger": { "kind": "button", "device": "hue-ts-entrance", "button": "2", "gesture": "press" },
            "effect": { "kind": "scene_toggle_cycle", "room": "kitchen-cooker" }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        match &binding.effect {
            Effect::SceneToggleCycle { room } => assert_eq!(room, "kitchen-cooker"),
            other => panic!("expected SceneToggleCycle, got {other:?}"),
        }
    }

    #[test]
    fn deserialize_soft_double_tap() {
        let json = r#"{
            "name": "kitchen-dbl",
            "trigger": { "kind": "button", "device": "hue-s-kitchen", "button": "on", "gesture": "soft_double_tap" },
            "effect": { "kind": "turn_off_all_zones" }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        match &binding.trigger {
            Trigger::Button { gesture, .. } => assert_eq!(*gesture, Gesture::SoftDoubleTap),
            other => panic!("expected Button, got {other:?}"),
        }
    }

    #[test]
    fn deserialize_toggle_with_confirm_off() {
        let json = r#"{
            "name": "ws-toggle",
            "trigger": { "kind": "button", "device": "sonoff-ts-ws", "button": "1", "gesture": "press" },
            "effect": { "kind": "toggle", "target": "sonoff-p-ws", "confirm_off_seconds": 1.0 }
        }"#;
        let binding: Binding = serde_json::from_str(json).unwrap();
        assert_eq!(binding.effect.confirm_off_seconds(), Some(1.0));
    }

    #[test]
    fn unknown_trigger_kind_rejected() {
        let json = r#"{
            "name": "bad",
            "trigger": { "kind": "explosion", "device": "x" },
            "effect": { "kind": "toggle", "target": "y" }
        }"#;
        assert!(serde_json::from_str::<Binding>(json).is_err());
    }

    #[test]
    fn unknown_effect_kind_rejected() {
        let json = r#"{
            "name": "bad",
            "trigger": { "kind": "button", "device": "x", "button": "1", "gesture": "press" },
            "effect": { "kind": "explode", "target": "y" }
        }"#;
        assert!(serde_json::from_str::<Binding>(json).is_err());
    }

    #[test]
    fn effect_room_accessor() {
        let e = Effect::SceneCycle { room: "kitchen".into() };
        assert_eq!(e.room(), Some("kitchen"));
        assert_eq!(e.target(), None);

        let e = Effect::SceneToggle { room: "bedroom".into() };
        assert_eq!(e.room(), Some("bedroom"));
        assert_eq!(e.target(), None);

        let e = Effect::Toggle { target: "plug".into(), confirm_off_seconds: None };
        assert_eq!(e.room(), None);
        assert_eq!(e.target(), Some("plug"));

        assert_eq!(Effect::TurnOffAllZones.room(), None);
        assert_eq!(Effect::TurnOffAllZones.target(), None);
    }
}
