//! The unified JSON configuration schema consumed by both subcommands.
//!
//! Generated by the Nix layer from `defineRooms`. The same file feeds
//! provisioning (group/scene/device reconciliation against z2m) and the
//! runtime daemon (room topology, scene cycle order, time-of-day slots).
//!
//! Schema sketch:
//!
//! ```jsonc
//! {
//!   // ieee → friendly_name canonical mapping. Source of truth for device
//!   // naming. Provisioning's reconcile_names phase uses this to rename any
//!   // z2m device whose current friendly_name doesn't match.
//!   "name_by_address": {
//!     "0x00178801086a51d2": "hue-s-some-switch",
//!     ...
//!   },
//!
//!   // Per-device options the runtime daemon needs to know about (motion
//!   // sensor timeouts, etc). Provisioning also writes these options to
//!   // the device on every reconcile.
//!   "devices": {
//!     "hue-ms-landing": {
//!       "kind": "motion-sensor",
//!       "occupancy_timeout_seconds": 60,
//!       "max_illuminance": 30,
//!       "options": { "occupancy_timeout": 60, "motion_sensitivity": "high" }
//!     },
//!     ...
//!   },
//!
//!   // The full room model. Each room is one zigbee group, optionally with
//!   // a parent room (for transitive ancestor/descendant invalidation).
//!   "rooms": [
//!     {
//!       "name": "kitchen-cooker",
//!       "group_name": "hue-lz-kitchen-cooker",
//!       "id": 15,
//!       "parent": "kitchen-all",
//!       "members": ["hue-l-kitchen-cooker-bottom/11", ...],
//!       "devices": [{"device": "hue-ts-kitchen-entrance", "button": 2}],
//!       "scenes": { /* see scenes.rs */ },
//!       "off_transition_seconds": 0.8,
//!       "motion_off_cooldown_seconds": 0
//!     },
//!     ...
//!   ],
//!
//!   // The same defaults block defineRooms accepts. Wall-switch tuning,
//!   // tap cycle window, etc.
//!   "defaults": { /* see defaults.rs */ }
//! }
//! ```

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};
use thiserror::Error;

pub mod bindings;
pub mod catalog;
pub mod defaults;
pub mod heating;
pub mod room;
pub mod scenes;
pub mod switch_model;
pub mod time_expr;

pub use bindings::{Binding, Effect, Trigger};
pub use catalog::{CommonFields, DeviceCatalogEntry, IeeeAddress};
pub use defaults::Defaults;
pub use heating::HeatingConfig;
pub use room::Room;
pub use scenes::{Scene, SceneSchedule, Slot, SlotName};
pub use switch_model::{Gesture, SwitchModel};
pub use time_expr::TimeExpr;

/// Top-level config. The Nix layer renders this as JSON; both subcommands
/// load it via [`Config::load_from_path`].
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Canonical ieee → friendly_name mapping. Empty when no renaming is
    /// desired (in which case provisioning skips its `reconcile_names`
    /// phase entirely).
    #[serde(default)]
    pub name_by_address: BTreeMap<IeeeAddress, String>,

    /// Device catalog keyed by friendly_name. Each entry carries the
    /// device kind plus per-kind metadata (motion sensor timeout, etc).
    #[serde(default)]
    pub devices: BTreeMap<String, DeviceCatalogEntry>,

    /// Switch model descriptors. Maps model names to their button layouts
    /// and z2m action string mappings. Referenced by `Switch` catalog
    /// entries via their `model` field.
    #[serde(default)]
    pub switch_models: BTreeMap<String, SwitchModel>,

    /// Ordered room list. Order matters for stable diff output and
    /// for the `lib.elem` parent-resolution semantics on the Nix side.
    pub rooms: Vec<Room>,

    /// Unified bindings: trigger + effect pairs. Replaces the old split
    /// between room device bindings and action rules. Generated by Nix
    /// from switch-to-room sugar and explicit action rules.
    #[serde(default)]
    pub bindings: Vec<Binding>,

    /// Behavioural defaults (cycle windows, brightness step, etc).
    #[serde(default)]
    pub defaults: Defaults,

    /// Optional heating subsystem configuration. Hosts without TRVs
    /// or wall thermostats omit this entirely.
    #[serde(default)]
    pub heating: Option<HeatingConfig>,

    /// Geographic location for sunrise/sunset calculations. Required
    /// when any scene schedule uses sun-relative time expressions.
    #[serde(default)]
    pub location: Option<crate::sun::Location>,
}

#[derive(Debug, Error)]
pub enum LoadError {
    #[error("could not read config file {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("config file {path} is not valid JSON: {source}")]
    Parse {
        path: String,
        #[source]
        source: serde_json::Error,
    },
}

impl Config {
    /// Read and parse a JSON config file. Validation happens later, when
    /// the [`crate::topology::Topology`] is built — schema-only errors
    /// surface here, semantic errors (parent cycles, missing devices) at
    /// topology-build time.
    pub fn load_from_path<P: AsRef<Path>>(path: P) -> Result<Self, LoadError> {
        let path_ref = path.as_ref();
        let path_str = path_ref.display().to_string();
        let raw = std::fs::read_to_string(path_ref).map_err(|source| LoadError::Io {
            path: path_str.clone(),
            source,
        })?;
        serde_json::from_str(&raw).map_err(|source| LoadError::Parse {
            path: path_str,
            source,
        })
    }

    /// Convenience for tests — parse from a string in memory.
    #[cfg(test)]
    pub fn from_json_str(s: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_room_list_parses() {
        let cfg: Config = serde_json::from_str(
            r#"{
                "rooms": []
            }"#,
        )
        .unwrap();
        assert!(cfg.rooms.is_empty());
        assert!(cfg.devices.is_empty());
        assert!(cfg.name_by_address.is_empty());
        assert!(cfg.switch_models.is_empty());
        assert!(cfg.bindings.is_empty());
    }

    #[test]
    fn unknown_top_level_field_is_rejected() {
        let err: Result<Config, _> = serde_json::from_str(
            r#"{
                "rooms": [],
                "ghost_field": 42
            }"#,
        );
        assert!(err.is_err(), "deny_unknown_fields should reject ghost_field");
    }
}
