# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/796b3df2-9359-48ed-9c0f-e1bdc3b0af9e";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/boot/firmware" =
    { device = "/dev/disk/by-uuid/F92E-2259";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/796b3df2-9359-48ed-9c0f-e1bdc3b0af9e";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/796b3df2-9359-48ed-9c0f-e1bdc3b0af9e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/796b3df2-9359-48ed-9c0f-e1bdc3b0af9e";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/796b3df2-9359-48ed-9c0f-e1bdc3b0af9e";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
