//! `mqtt-controller` — unified provisioner and runtime controller for the
//! zigbee2mqtt-driven lighting setup on raspi5m.
//!
//! Replaces two pieces of the old stack:
//!
//!   * `pkg/hue-setup/hue_setup.py` — the declarative z2m group/scene
//!     reconciler. Now lives under [`provision`].
//!   * `modules/nixos/mqtt-automations.nix` + the bento config it rendered
//!     — the runtime rule engine that translated button presses, motion
//!     events, and group state into z2m commands. Now lives under
//!     [`controller`] and [`mqtt`].
//!
//! Both modes share the same JSON config schema generated by Nix
//! (see [`config::Config`]). One binary, two subcommands wired up in
//! [`main`](../bin/mqtt-controller/main.rs).

pub mod config;
pub mod controller;
pub mod daemon;
pub mod domain;
pub mod entities;
pub mod logic;
pub mod mqtt;
pub mod provision;
pub mod sun;
pub mod tass;
pub mod time;
pub mod topology;
pub mod web;
