[
  ./alien-filesystems.nix
  ./audio-autoswitch.nix
  ./audio-quirks.nix
  ./bluetooth.nix
  ./bootloader-grub.nix
  ./bootloader-ipxe.nix
  ./bootloader-lanzaboote.nix
  ./bootloader-systemd.nix
  ./cosmic.nix
  ./cpu.nix
  ./email.nix
  ./cups.nix
  ./docker.nix
  ./env-settings-linux-desktop.nix
  ./env-settings-linux.nix
  ./gnome.nix
  ./iperf.nix
  ./gnome-minimal-hotkeys.nix
  ./gnome-extensions.nix
  ./kernel-settings.nix
  ./keyd-super-remap.nix
  ./keyring.nix
  ./ledger.nix
  ./llm.nix
  ./locale-ie.nix
  ./metrics.nix
  ./networking-desktop.nix
  ./networking.nix
  ./nix-ld.nix
  ./nushell.nix
  ./oracle-cloud.nix
  ./overlay.nix
  ./power-amd.nix
  ./power.nix
  ./realtek-kernel-hack.nix
  ./rocm.nix
  ./router.nix
  ./smartd.nix
  ./ssh.nix
  ./sudo.nix
  ./tailscale.nix
  ./trezor.nix
  ./uhk-keyboard.nix
  ./virt-manager.nix
  ./zfs-ssh-initrd.nix
  ./zfs.nix
  ./zsh.nix
  ./zswap.nix
]
