[
  ./alien-filesystems.nix
  ./bluetooth.nix
  ./bootloader-grub.nix
  ./bootloader-lanzaboote.nix
  ./bootloader-systemd.nix
  ./builders.nix
  ./cpu.nix
  ./email.nix
  ./cups.nix
  ./docker.nix
  ./env-settings-linux.nix
  ./gnome.nix
  ./gnome-minimal-hotkeys.nix
  ./kernel-settings.nix
  ./keyd-super-remap.nix
  ./ledger.nix
  ./llm.nix
  ./locale-ie.nix
  ./networking.nix
  ./nix-ld.nix
  ./overlay.nix
  ./power.nix
  ./realtek-kernel-hack.nix
  ./rocm.nix
  ./router.nix
  ./smartd.nix
  ./ssh-permissive.nix
  ./ssh-safe.nix
  ./sudo.nix
  ./tailscale.nix
  ./trezor.nix
  ./uhk-keyboard.nix
  ./virt-manager.nix
  ./zfs-ssh-initrd.nix
  ./zfs.nix
  ./zsh.nix
  ./zswap.nix
]
