[
  ./alien-filesystems.nix
  ./audio.nix
  ./audio-autoswitch.nix
  ./audio-quirks.nix
  ./bluetooth.nix
  ./bootloader-grub.nix
  ./bootloader-ipxe.nix
  ./bootloader-lanzaboote.nix
  ./bootloader-systemd.nix
  ./cosmic.nix
  ./cpu.nix
  ./display-manager.nix
  ./dev-adb.nix
  ./dev-wireshark.nix
  ./email.nix
  ./fingerprint.nix
  ./cups.nix
  ./docker.nix
  ./env-settings-linux-desktop.nix
  ./env-settings-linux.nix
  ./gnome.nix
  ./iperf.nix
  ./gnome-minimal-hotkeys.nix
  ./gnome-extensions.nix
  ./kanata-super-remap.nix
  ./kde.nix
  ./kdeconnect.nix
  ./kernel-settings.nix
  ./keyring.nix
  ./ledger.nix
  ./llm.nix
  ./locale-ie.nix
  ./metrics.nix
  ./networking-desktop.nix
  ./networking.nix
  ./nvidia-hybrid.nix
  ./nix-ld.nix
  ./nushell.nix
  ./oracle-cloud.nix
  ./overlay.nix
  ./power-generic.nix
  ./power-profiles.nix
  ./power-refresh-rate.nix
  ./power-suspend-quirks.nix
  ./realtek-kernel-hack.nix
  ./rocm.nix
  ./router.nix
  ./smartd.nix
  ./ssh.nix
  ./steam.nix
  ./sudo.nix
  ./tailscale.nix
  ./trezor.nix
  ./uhk-keyboard.nix
  ./virt-manager.nix
  ./zfs-ssh-initrd.nix
  ./zfs.nix
  ./zsh.nix
  ./zswap.nix
]
