[
  ./_desktop.nix
  ./alien-filesystems.nix
  ./cpu.nix
  ./email.nix
  ./cups.nix
  ./env-settings-linux.nix
  ./env-settings.nix
  ./fonts-apple.nix
  ./fonts-nerd.nix
  ./gnome.nix
  ./gnome-minimal-hotkeys.nix
  ./grub.nix
  ./home-manager.nix
  ./kernel-settings.nix
  ./keyd-super-remap.nix
  ./ledger.nix
  ./lib.nix
  ./locale-ie.nix
  ./networking.nix
  ./nix-ld.nix
  ./nix.nix
  ./overlay.nix
  ./power.nix
  ./realtek-kernel-hack.nix
  ./router.nix
  ./smartd.nix
  ./ssh-permissive.nix
  ./ssh-safe.nix
  ./sudo.nix
  ./trezor.nix
  ./uhk-keyboard.nix
  ./virt-manager.nix
  ./zfs-ssh-initrd.nix
  ./zfs.nix
  ./zsh.nix
  ./zswap.nix
]
